Typos and other small fixes

diff --git a/git/git-credential-pass b/git/git-credential-pass
--- a/git/git-credential-pass
+++ b/git/git-credential-pass
@@ -44,7 +44,7 @@ while read -r line; do
 		     # present we are of no help.
     '');; # Ignore empty lines.
     *)
-      echo "Error: Invalide line on stdin: $line" >&2
+      echo "Error: Invalid line on stdin: $line" >&2
       exit 1
       ;;
   esac
